* Haec fābula


* "You need to..." using oportet
Oportet means "it is necessary" and is used to say someone needs to do something.
Example from John 3 in the Vulgate: "oportet vōs nāscī dēnuō."
This can be translated as "you must be born again" or, more literally, "it is necessary that you be born again."
(In this example nāscī is an infinitive -- if it doesn't look like infinitives that you are familiar with, that's because the verb is deponent).

The accusative case is used to indicate who needs to do the thing.
Example: Tē oportet scrībere = It is necessary for you to write = You must write.

* "It's time for..." using gerunds
The clock in this story uses a genitive gerund to say what its time for.
A gerund is a verb that functions like a noun. Example: "Running is fun." "Running" is a gerund.

An example of saying that it's time to return home:
"Est tempus revertendī ad domum." Literally: "It is the time of returning to home."

The genitive gerund can usually be formed by tacking -ndī onto your verb, like so: revertere -> revertendī

An example of this usage can be found in Ecclesiates 3:2:
"tempus nāscendī et tempus moriendī" = A time of being born and a time of dying = A time to be born and a time to die.

* "He likes..." using placere
To say someone likes something, we use a construction using placere, which means "to please."
So "I like the cat" is "Fēlīs mihī placet" (literally, "the cat is pleasing to me").
Note that "cat" is in the nominative and "mihī" is in the dative.

An example with the imperfect tense: "Basipila placēbat Haroldō" = Baseball was pleasing to Harold = Harold liked baseball.
